---
- name: Install GavoDaCHS
  hosts: isolvm

  vars_files:
    - vars.yml

  remote_user: "{{ admin_user }}"

  pre_tasks:
  - name: Install sudo
    apt:
      name: sudo
      state: present


  - name: Add user to sudoers
    lineinfile:
      path: /etc/sudoers
      line: "{{ admin_user }} ALL=(ALL:ALL) ALL"
      state: present
  become: true
  become_method: su
  become_user: root
  tasks:
  - name: Install gavo
    include_role:
      name: install-gavo

  - name: Import data
    include_role:
      name: load-data
    vars:
      data_name: "{{ item.data_name }}"
      rd_url: "{{ item.rd_url }}"
      data_url: "{{ item.data_url }}"
      data_checksum: "md5:{{ item.checksum }}"
    loop:
      - "{{ data_sources.arihip }}"

  - name: run server
    include_role:
      name: restart-and-serve
