---
- name: Install GavoDaCHS
  hosts: localvm

  vars_files:
    - vars.yml

  remote_user: "{{ admin_user }}"

  pre_tasks:
  - name: Install sudo
    apt:
      name: sudo
      state: present


  - name: Add user to sudoers
    lineinfile:
      path: /etc/sudoers
      line: '{{ admin_user }} ALL=(ALL:ALL) ALL'
      state: present
  become: true
  become_method: su
  become_user: root
  tasks:
  - name: Install gavo
    include_role:
      name: install-gavo

  - name: Import data
    with_items: "{{ data_sources | dict2items }}"
    include_role:
      name: load-data
    vars:
      data_idx: "{{ item }}"

  - name: run server
    include_role:
      name: restart-and-serve
