---
- name: Install GAVO DaCHS
  hosts: dev_group_name
  vars_files:
    - vars.yml
  remote_user: "{{ admin_user }}"
  pre_tasks:
  - name: Install sudo
    apt:
      pkg:
        - sudo
        - iptables
        - acl
        - gpg

  - name: Add user to sudoers
    lineinfile:
      path: /etc/sudoers
      line: "{{ admin_user }} ALL=(ALL:ALL) ALL"
      state: present

  become: true
  become_method: su
  become_user: root

  tasks:
  - name: Install GAVO DaCHS
    include_role:
      name: install-gavo
    vars:
        version: "{{ item.version }}"

  - name: Configure PostgreSQL
    include_role:
      name: configure-db

  - name: Import data into GAVO DaCHS
    include_role:
      name: load-data
    vars:
      data_name: "{{ item.data_name }}"
      rd_url: "{{ item.rd_url }}"
      data_url: "{{ item.data_url }}"
      checksum_algorithm: "{{ item.checksum_algorithm }}"
      data_checksum: "{{ item.data_checksum }}"
    loop:
      - "{{ data_sources.arihip }}"

  - name: Run and serve GAVO DaCHS
    include_role:
      name: restart-and-serve
