---
- block:
  - name: Stop server
    command: /etc/init.d/dachs stop

  - name: Setup Dachs server
    template:
      src: gavo-service.j2
      dest: /etc/systemd/system/gavo.service

  - name: Start server
    ansible.builtin.systemd:
      name: gavo
      state: started
      enabled: yes
      daemon_reload: yes
  become: yes
  become_method: sudo
  become_user: root