---
# This role will kill the currently running GAVO DaCHS server, send the
# configuration file to the correct place and then restart the server to serve
# the DaCHS service.

- name: Restart the GAVO DaCHS service and serve the service
  block:
  - name: Stop the server
    command: /etc/init.d/dachs stop
  - name: Setup GAVO DaCHS server configuration
    template:
      src: gavo-service.j2
      dest: /etc/systemd/system/gavo.service
  - name: Start the GAVO DaCHS server
    ansible.builtin.systemd:
      name: gavo
      state: started
      enabled: true
      daemon_reload: true
  - name: Allow connections on 8080
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 8080
      jump: ACCEPT
  become: true
  become_method: sudo
  become_user: root
