---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: apt

- name: Ensure gavodachs2-server is in the apt reposorory
  block:
  - name: Ensurre gpg is installed
    apt:
      name: gpg
      state: present

  - name: Make the apt key file
    file:
      path: /etc/apt/trusted.gpg.d/gavo-archive.key.asc
      state: touch

  - name: Add the apt key to file
    ansible.builtin.apt_key:
      id: D8C139FC
      url: https://docs.g-vo.org/archive-key.asc
      keyring: /etc/apt/trusted.gpg.d/gavo-archive.key.asc

  - name: Add the apt reposotory
    ansible.builtin.apt_repository:
      repo: deb http://vo.ari.uni-heidelberg.de/debian release main
  when: '"gavodachs2-server" not in ansible_facts.packages'
  become: true
  become_method: sudo
  become_user: root

- name: Install and add configuration
  block:
  - name: Install gavodachs
    apt:
      name: gavodachs2-server
      state: present

  - name: Make and write to gavo.rc
    template:
      src: gavo.rc.j2
      dest: /etc/gavo.rc
  become: true
  become_method: sudo
  become_user: root
