---
# This role downloads and imports data into GAVO DaCHS. Each step is done as
# root.

- name: Download and import data into GAVO DaCHS
  block:
  - name: Create directory to store data for import
    ansible.builtin.file:
      path: "/var/gavo/inputs/{{ data_name }}/data/"
      group: gavo
      owner: dachsroot
      state: directory
  - name: Get the resource descriptor for the data
    template:
      src:  arihip_q.rd.j2
      dest: "/var/gavo/inputs/{{ data_name }}/q.rd"
  - name: Get the data
    ansible.builtin.get_url:
      url: "{{ data_url }}"
      dest: "/var/gavo/inputs/{{ data_name }}/data/data.txt.gz"
      checksum: "{{ checksum_algorithm }}:{{ data_checksum }}"
      group: gavo
      owner: dachsroot

  # TODO: Not strictly necessary but would be good to get working for completeness
  #- name: Test Resource Descriptor
  #  assert:
  #    that:
  #      - "dachs test {{ data_name }}/q == 0"
  #    fail_msg: "q.rd file for {{ data_name }} failed test"

  - name: Import the data into DaCHS
    ansible.builtin.command: "{{ loop_item }} {{ data_name }}/q"
    with_items:
      - dachs imp
      - dachs limits
      # - dachs pub
    loop_control:
      loop_var: loop_item
  become: true
  become_method: sudo
  become_user: root
