---
- block:
  - name: Make the data file
    ansible.builtin.file:
      path: "/var/gavo/inputs/{{ data_name }}/data/"
      group: gavo
      owner: dachsroot
      state: directory

  - name: Download Test Resource Descriptor
    ansible.builtin.get_url:
      url: "{{ rd_url }}"
      dest: "/var/gavo/inputs/{{ data_name }}/q.rd"
      group: gavo
      owner: dachsroot

  - name: Download test Data
    ansible.builtin.get_url:
      url: "{{ data_url }}"
      dest: "/var/gavo/inputs/{{ data_name }}/data/data.txt.gz"
      checksum: "{{ checksum_algorithm }}:{{ data_checksum }}"
      group: gavo
      owner: dachsroot

  # TODO: Not strictly necessary but would be good to get working for completeness
  #- name: Test Resource Descriptor
  #  assert:
  #    that:
  #      - "dachs test {{ data_name }}/q == 0"
  #    fail_msg: "q.rd file for {{ data_name }} failed test"

  - name: Import Data
    ansible.builtin.command: "{{ loop_item }} {{ data_name }}/q"
    with_items:
      - dachs imp
      - dachs limits
    loop_control:
      loop_var: loop_item

  become: true
  become_method: sudo
  become_user: root
